#!/usr/bin/env bash

# Run the complete GROMACS workflow for every protein PDB in input/, then
# perform a standard, reproducible analysis of the production trajectory.
#
# Designed for GROMACS 2025.1 and the current PLA workflow. Existing 01-09
# scripts are intentionally left untouched.

set -Eeuo pipefail
shopt -s nullglob

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
INPUT_DIR="${INPUT_DIR:-${ROOT_DIR}/input}"
RESULTS_DIR="${RESULTS_DIR:-${ROOT_DIR}/results}"

DEFAULT_GMX=/home/rduser/software/gromacs/gromacs-2025.1/build/bin/gmx
if [[ -z "${GMX+x}" ]]; then
    if [[ -x "${DEFAULT_GMX}" ]]; then
        GMX="${DEFAULT_GMX}"
    else
        GMX=gmx
    fi
fi

FORCE_FIELD="${FORCE_FIELD:-charmm27}"
WATER_MODEL="${WATER_MODEL:-tip3p}"
SALT_CONC="${SALT_CONC:-0.15}"
BOX_DISTANCE_NM="${BOX_DISTANCE_NM:-1.0}"
ANALYSIS_BEGIN_PS="${ANALYSIS_BEGIN_PS:-50000}"
CORE_RMSD="${CORE_RMSD:-1}"
CORE_RESID_START="${CORE_RESID_START:-29}"
CORE_RESID_END="${CORE_RESID_END:-298}"

# These are the standard groups generated by pdb2gmx for a protein system.
# They can be overridden for a non-standard system.
SYSTEM_GROUP="${SYSTEM_GROUP:-0}"
PROTEIN_GROUP="${PROTEIN_GROUP:-1}"
CALPHA_GROUP="${CALPHA_GROUP:-3}"
BACKBONE_GROUP="${BACKBONE_GROUP:-4}"

ANALYSIS_ONLY="${ANALYSIS_ONLY:-0}"
SIMULATION_ONLY="${SIMULATION_ONLY:-0}"
FORCE_ANALYSIS="${FORCE_ANALYSIS:-0}"

if [[ -v EM_MDRUN_ARGS ]]; then
    read -r -a EM_MDRUN_ARGS_ARRAY <<< "${EM_MDRUN_ARGS}"
else
    EM_MDRUN_ARGS_ARRAY=(-nb gpu)
fi

if [[ -v MD_MDRUN_ARGS ]]; then
    read -r -a MD_MDRUN_ARGS_ARRAY <<< "${MD_MDRUN_ARGS}"
else
    MD_MDRUN_ARGS_ARRAY=(-nb gpu -pme gpu -update gpu)
fi

log() {
    printf '[%(%F %T)T] %s\n' -1 "$*"
}

die() {
    log "ERROR: $*"
    exit 1
}

run_optional() {
    local label=$1
    shift
    log "Analysis: ${label}"
    if ! "$@"; then
        log "WARNING: ${label} failed; simulation data were kept and the remaining analyses will continue."
        return 0
    fi
}

need_output() {
    [[ "${FORCE_ANALYSIS}" == 1 || ! -s "$1" ]]
}

extract_energy() {
    local term=$1
    local output=$2
    local begin_ps=${3:-0}

    if need_output "${output}"; then
        printf '%s\n0\n' "${term}" | "${GMX}" energy \
            -f md.edr \
            -o "${output}" \
            -b "${begin_ps}"
    fi
}

extract_stage_energy() {
    local edr=$1
    local term=$2
    local output=$3

    [[ -s "${edr}" ]] || return 0
    if need_output "${output}"; then
        printf '%s\n0\n' "${term}" | "${GMX}" energy \
            -f "${edr}" \
            -o "${output}"
    fi
}

analyze_gyrate() {
    if need_output analysis/gyrate_equilibrium.xvg; then
        "${GMX}" gyrate \
            -s analysis/protein.tpr \
            -f analysis/md_protein_noPBC.xtc \
            -sel 'group "Protein"' \
            -o analysis/gyrate_equilibrium.xvg \
            -b "${ANALYSIS_BEGIN_PS}" \
            -tu ns
    fi
}

analyze_sasa() {
    if need_output analysis/sasa_equilibrium.xvg; then
        "${GMX}" sasa \
            -s analysis/protein.tpr \
            -f analysis/md_protein_noPBC.xtc \
            -surface 'group "Protein"' \
            -output 'group "Protein"' \
            -o analysis/sasa_equilibrium.xvg \
            -or analysis/sasa_per_residue_equilibrium.xvg \
            -b "${ANALYSIS_BEGIN_PS}" \
            -tu ns
    fi
}

analyze_hbond() {
    if need_output analysis/hbond_protein_equilibrium.xvg; then
        "${GMX}" hbond \
            -s analysis/protein.tpr \
            -f analysis/md_protein_noPBC.xtc \
            -r 'group "Protein"' \
            -t 'group "Protein"' \
            -num analysis/hbond_protein_equilibrium.xvg \
            -b "${ANALYSIS_BEGIN_PS}" \
            -tu ns
    fi
}

analyze_dssp() {
    if need_output analysis/dssp_equilibrium.dat; then
        "${GMX}" dssp \
            -s analysis/protein.tpr \
            -f analysis/md_protein_noPBC.xtc \
            -sel 'group "Protein"' \
            -o analysis/dssp_equilibrium.dat \
            -num analysis/dssp_count_equilibrium.xvg \
            -b "${ANALYSIS_BEGIN_PS}" \
            -tu ns
    fi
}

analyze_periodic_distance() {
    if need_output analysis/min_periodic_distance_equilibrium.xvg; then
        printf '%s\n' "${PROTEIN_GROUP}" | "${GMX}" mindist \
            -s analysis/protein.tpr \
            -f analysis/md_protein_noPBC.xtc \
            -od analysis/min_periodic_distance_equilibrium.xvg \
            -pi \
            -b "${ANALYSIS_BEGIN_PS}"
    fi
}

write_xvg_stats() {
    local label=$1
    local file=$2
    local column=${3:-2}

    [[ -s "${file}" ]] || return 0
    awk -v label="${label}" -v col="${column}" '
        !/^[@#]/ && NF >= col {
            value=$col
            n++
            sum+=value
            sumsq+=value*value
            if (n==1 || value<min) min=value
            if (n==1 || value>max) max=value
        }
        END {
            if (n>0) {
                mean=sum/n
                variance=sumsq/n-mean*mean
                if (variance<0 && variance>-1e-12) variance=0
                sd=sqrt(variance)
                printf "%s\t%d\t%.8g\t%.8g\t%.8g\t%.8g\n", label,n,mean,sd,min,max
            }
        }
    ' "${file}" >> analysis/summary.tsv
}

write_rmsd_window_stats() {
    local label=${1:-RMSD_Backbone_equilibrium_nm}
    local file=${2:-analysis/rmsd_backbone.xvg}
    local begin_ns
    begin_ns=$(awk -v ps="${ANALYSIS_BEGIN_PS}" 'BEGIN { printf "%.10g", ps/1000 }')

    [[ -s "${file}" ]] || return 0
    awk -v begin="${begin_ns}" -v label="${label}" '
        !/^[@#]/ && $1>=begin {
            n++
            sum+=$2
            sumsq+=$2*$2
            if (n==1 || $2<min) min=$2
            if (n==1 || $2>max) max=$2
        }
        END {
            if (n>0) {
                mean=sum/n
                variance=sumsq/n-mean*mean
                if (variance<0 && variance>-1e-12) variance=0
                sd=sqrt(variance)
                printf "%s\t%d\t%.8g\t%.8g\t%.8g\t%.8g\n", label,n,mean,sd,min,max
            }
        }
    ' "${file}" >> analysis/summary.tsv
}

prepare_and_simulate() {
    local source_pdb=$1

    if [[ ! -s input.pdb ]]; then
        cp -- "${source_pdb}" input.pdb
    fi

    if [[ ! -s md.tpr ]]; then
        if [[ ! -s processed.gro || ! -s topol.top || ! -s posre.itp ]]; then
            log '01/09 pdb2gmx'
            "${GMX}" pdb2gmx \
                -f input.pdb \
                -o processed.gro \
                -p topol.top \
                -i posre.itp \
                -ff "${FORCE_FIELD}" \
                -water "${WATER_MODEL}" \
                -ignh
        else
            log '01/09 pdb2gmx: existing outputs found, skipped'
        fi

        if [[ ! -s box.gro ]]; then
            log '02/09 editconf'
            "${GMX}" editconf \
                -f processed.gro \
                -o box.gro \
                -c \
                -d "${BOX_DISTANCE_NM}" \
                -bt dodecahedron
        else
            log '02/09 editconf: existing output found, skipped'
        fi

        if [[ ! -s solv.gro ]]; then
            log '03/09 solvate'
            "${GMX}" solvate \
                -cp box.gro \
                -cs spc216.gro \
                -o solv.gro \
                -p topol.top
        else
            log '03/09 solvate: existing output found, skipped'
        fi

        if [[ ! -s ions.tpr ]]; then
            log '04/09 prepare ions'
            "${GMX}" grompp \
                -f "${ROOT_DIR}/mdp/ions.mdp" \
                -c solv.gro \
                -p topol.top \
                -o ions.tpr \
                -po ions_mdout.mdp
        else
            log '04/09 prepare ions: existing output found, skipped'
        fi

        if [[ ! -s ions.gro ]]; then
            log '05/09 add ions'
            printf 'SOL\n' | "${GMX}" genion \
                -s ions.tpr \
                -o ions.gro \
                -p topol.top \
                -pname NA \
                -nname CL \
                -neutral \
                -conc "${SALT_CONC}"
        else
            log '05/09 add ions: existing output found, skipped'
        fi

        if [[ ! -s em.gro ]]; then
            log '06/09 energy minimization'
            "${GMX}" grompp \
                -f "${ROOT_DIR}/mdp/em.mdp" \
                -c ions.gro \
                -p topol.top \
                -o em.tpr \
                -po em_mdout.mdp
            "${GMX}" mdrun -deffnm em "${EM_MDRUN_ARGS_ARRAY[@]}"
        else
            log '06/09 energy minimization: existing output found, skipped'
        fi

        if [[ ! -s nvt.gro ]]; then
            log '07/09 NVT equilibration'
            "${GMX}" grompp \
                -f "${ROOT_DIR}/mdp/nvt.mdp" \
                -c em.gro \
                -r em.gro \
                -p topol.top \
                -o nvt.tpr \
                -po nvt_mdout.mdp
            "${GMX}" mdrun -deffnm nvt "${MD_MDRUN_ARGS_ARRAY[@]}"
        else
            log '07/09 NVT equilibration: existing output found, skipped'
        fi

        if [[ ! -s npt.gro ]]; then
            log '08/09 NPT equilibration'
            "${GMX}" grompp \
                -f "${ROOT_DIR}/mdp/npt.mdp" \
                -c nvt.gro \
                -r nvt.gro \
                -t nvt.cpt \
                -p topol.top \
                -o npt.tpr \
                -po npt_mdout.mdp
            "${GMX}" mdrun -deffnm npt "${MD_MDRUN_ARGS_ARRAY[@]}"
        else
            log '08/09 NPT equilibration: existing output found, skipped'
        fi

        log '09/09 prepare production MD'
        "${GMX}" grompp \
            -f "${ROOT_DIR}/md.mdp" \
            -c npt.gro \
            -t npt.cpt \
            -p topol.top \
            -o md.tpr \
            -po md_mdout.mdp
    else
        log '01-09 preparation: md.tpr already exists, skipped'
    fi

    if [[ -s md.log ]] && grep -q 'Finished mdrun' md.log && [[ -s md.xtc && -s md.edr && -s md.gro ]]; then
        log '09/09 production MD: completed outputs found, skipped'
        return 0
    fi

    log '09/09 production MD'
    local restart_args=()
    if [[ -s md.cpt ]]; then
        restart_args=(-cpi md.cpt -append)
        log 'Continuing production MD from md.cpt'
    fi
    "${GMX}" mdrun \
        -s md.tpr \
        -deffnm md \
        "${restart_args[@]}" \
        "${MD_MDRUN_ARGS_ARRAY[@]}"
}

analyze_trajectory() {
    [[ -s md.tpr ]] || die "$(pwd)/md.tpr is missing"
    [[ -s md.xtc ]] || die "$(pwd)/md.xtc is missing"
    [[ -s md.edr ]] || die "$(pwd)/md.edr is missing"

    mkdir -p analysis

    {
        printf 'analysis_begin_ps=%s\n' "${ANALYSIS_BEGIN_PS}"
        printf 'system_group=%s\n' "${SYSTEM_GROUP}"
        printf 'protein_group=%s\n' "${PROTEIN_GROUP}"
        printf 'calpha_group=%s\n' "${CALPHA_GROUP}"
        printf 'backbone_group=%s\n' "${BACKBONE_GROUP}"
        printf 'core_rmsd=%s\n' "${CORE_RMSD}"
        printf 'core_resid_start=%s\n' "${CORE_RESID_START}"
        printf 'core_resid_end=%s\n' "${CORE_RESID_END}"
        "${GMX}" --version
    } > analysis/run_config.txt

    if need_output analysis/trajectory_check.txt; then
        log 'Analysis: trajectory integrity check'
        "${GMX}" check -f md.xtc > analysis/trajectory_check.txt 2>&1
    fi

    if need_output analysis/protein.tpr; then
        log 'Analysis: create protein-only run input'
        printf '%s\n' "${PROTEIN_GROUP}" | "${GMX}" convert-tpr \
            -s md.tpr \
            -o analysis/protein.tpr
    fi

    # Keep only the protein in the corrected trajectory. This is much smaller
    # than writing the full solvated system and is sufficient for all analyses
    # below. The protein is molecule-whole and centered in the compact unit cell.
    if need_output analysis/md_protein_noPBC.xtc; then
        log 'Analysis: remove PBC and write protein-only trajectory'
        printf '%s\n%s\n' "${PROTEIN_GROUP}" "${PROTEIN_GROUP}" | \
            "${GMX}" trjconv \
                -s md.tpr \
                -f md.xtc \
                -o analysis/md_protein_noPBC.xtc \
                -center \
                -pbc mol \
                -ur compact
    fi

    if need_output analysis/rmsd_backbone.xvg; then
        log 'Analysis: backbone RMSD (full trajectory)'
        printf '%s\n%s\n' "${BACKBONE_GROUP}" "${BACKBONE_GROUP}" | \
            "${GMX}" rms \
                -s analysis/protein.tpr \
                -f analysis/md_protein_noPBC.xtc \
                -o analysis/rmsd_backbone.xvg \
                -tu ns
    fi

    if [[ "${CORE_RMSD}" == 1 ]]; then
        if need_output analysis/core_backbone.ndx; then
            log "Analysis: select core backbone residues ${CORE_RESID_START}-${CORE_RESID_END}"
            "${GMX}" select \
                -s analysis/protein.tpr \
                -on analysis/core_backbone.ndx \
                -select "group \"Backbone\" and resid ${CORE_RESID_START} to ${CORE_RESID_END}"
        fi
        if need_output analysis/rmsd_core_backbone.xvg; then
            log 'Analysis: core-backbone RMSD (full trajectory)'
            printf '0\n0\n' | "${GMX}" rms \
                -s analysis/protein.tpr \
                -f analysis/md_protein_noPBC.xtc \
                -n analysis/core_backbone.ndx \
                -o analysis/rmsd_core_backbone.xvg \
                -tu ns
        fi
    fi

    if need_output analysis/rmsf_calpha_equilibrium.xvg; then
        log 'Analysis: C-alpha RMSF (equilibrium window)'
        printf '%s\n' "${CALPHA_GROUP}" | \
            "${GMX}" rmsf \
                -s analysis/protein.tpr \
                -f analysis/md_protein_noPBC.xtc \
                -o analysis/rmsf_calpha_equilibrium.xvg \
                -res \
                -b "${ANALYSIS_BEGIN_PS}"
    fi

    run_optional 'radius of gyration' analyze_gyrate
    run_optional 'solvent-accessible surface area' analyze_sasa
    run_optional 'protein-protein hydrogen bonds' analyze_hbond
    run_optional 'DSSP secondary structure' analyze_dssp
    run_optional 'minimum distance to periodic image' analyze_periodic_distance

    run_optional 'production temperature' extract_energy Temperature analysis/temperature_equilibrium.xvg "${ANALYSIS_BEGIN_PS}"
    run_optional 'production pressure' extract_energy Pressure analysis/pressure_equilibrium.xvg "${ANALYSIS_BEGIN_PS}"
    run_optional 'production density' extract_energy Density analysis/density_equilibrium.xvg "${ANALYSIS_BEGIN_PS}"
    run_optional 'production potential energy' extract_energy Potential analysis/potential_equilibrium.xvg "${ANALYSIS_BEGIN_PS}"
    run_optional 'minimization potential energy' extract_stage_energy em.edr Potential analysis/em_potential.xvg
    run_optional 'NVT temperature' extract_stage_energy nvt.edr Temperature analysis/nvt_temperature.xvg
    run_optional 'NPT temperature' extract_stage_energy npt.edr Temperature analysis/npt_temperature.xvg
    run_optional 'NPT pressure' extract_stage_energy npt.edr Pressure analysis/npt_pressure.xvg
    run_optional 'NPT density' extract_stage_energy npt.edr Density analysis/npt_density.xvg

    {
        grep -Ei 'converged|Fmax|Potential Energy' em.log 2>/dev/null || true
        grep -Ei 'fatal|error|LINCS WARNING|nan|killed|segmentation|Finished mdrun|Performance' md.log 2>/dev/null || true
    } > analysis/run_qc.txt

    printf 'metric\tn\tmean\tsd\tmin\tmax\n' > analysis/summary.tsv
    write_xvg_stats RMSD_Backbone_full_nm analysis/rmsd_backbone.xvg
    write_rmsd_window_stats
    write_xvg_stats RMSD_Core_Backbone_full_nm analysis/rmsd_core_backbone.xvg
    write_rmsd_window_stats RMSD_Core_Backbone_equilibrium_nm analysis/rmsd_core_backbone.xvg
    write_xvg_stats RMSF_Calpha_equilibrium_nm analysis/rmsf_calpha_equilibrium.xvg
    write_xvg_stats Radius_of_gyration_equilibrium_nm analysis/gyrate_equilibrium.xvg
    write_xvg_stats SASA_equilibrium_nm2 analysis/sasa_equilibrium.xvg
    write_xvg_stats Protein_Hbonds_equilibrium analysis/hbond_protein_equilibrium.xvg
    write_xvg_stats Min_periodic_distance_equilibrium_nm analysis/min_periodic_distance_equilibrium.xvg
    write_xvg_stats Temperature_equilibrium_K analysis/temperature_equilibrium.xvg
    write_xvg_stats Pressure_equilibrium_bar analysis/pressure_equilibrium.xvg
    write_xvg_stats Density_equilibrium_kg_m3 analysis/density_equilibrium.xvg
    write_xvg_stats Potential_equilibrium_kJ_mol analysis/potential_equilibrium.xvg
    write_xvg_stats EM_potential_kJ_mol analysis/em_potential.xvg
    write_xvg_stats NVT_temperature_K analysis/nvt_temperature.xvg
    write_xvg_stats NPT_temperature_K analysis/npt_temperature.xvg
    write_xvg_stats NPT_pressure_bar analysis/npt_pressure.xvg
    write_xvg_stats NPT_density_kg_m3 analysis/npt_density.xvg

    awk '!/^[@#]/{print $1, $2}' analysis/rmsf_calpha_equilibrium.xvg | \
        sort -k2,2nr | head -20 > analysis/rmsf_top20.tsv

    log 'Analysis completed; see analysis/summary.tsv'
}

command -v "${GMX}" >/dev/null 2>&1 || die "GROMACS executable not found: ${GMX}"
[[ -d "${INPUT_DIR}" ]] || die "Input directory not found: ${INPUT_DIR}"
[[ "${ANALYSIS_ONLY}" != 1 || "${SIMULATION_ONLY}" != 1 ]] || \
    die 'ANALYSIS_ONLY=1 and SIMULATION_ONLY=1 cannot be used together'

mkdir -p "${RESULTS_DIR}"

pdb_files=()
if (( $# > 0 )); then
    for requested in "$@"; do
        if [[ -f "${requested}" ]]; then
            pdb_files+=("$(cd -- "$(dirname -- "${requested}")" && pwd)/$(basename -- "${requested}")")
        elif [[ -f "${INPUT_DIR}/${requested}" ]]; then
            pdb_files+=("${INPUT_DIR}/${requested}")
        else
            die "PDB not found: ${requested}"
        fi
    done
else
    pdb_files=("${INPUT_DIR}"/*.pdb "${INPUT_DIR}"/*.PDB)
fi

(( ${#pdb_files[@]} > 0 )) || die "No PDB files found in ${INPUT_DIR}"

log "Found ${#pdb_files[@]} PDB file(s); processing sequentially."

for source_pdb in "${pdb_files[@]}"; do
    pdb_filename="$(basename -- "${source_pdb}")"
    target_name="${pdb_filename%.*}"
    target_dir="${RESULTS_DIR}/${target_name}"

    mkdir -p "${target_dir}"
    log "===== ${target_name} ====="

    (
        cd "${target_dir}"
        exec > >(tee -a pipeline.log) 2>&1
        trap 'log "FAILED: ${target_name} at line ${LINENO}"' ERR

        if [[ "${ANALYSIS_ONLY}" != 1 ]]; then
            prepare_and_simulate "${source_pdb}"
        fi

        if [[ "${SIMULATION_ONLY}" != 1 ]]; then
            analyze_trajectory
        fi
    )
done

if [[ "${SIMULATION_ONLY}" != 1 ]]; then
    aggregate_tmp="${RESULTS_DIR}/summary_all.tsv.tmp"
    aggregate="${RESULTS_DIR}/summary_all.tsv"
    printf 'target\tmetric\tn\tmean\tsd\tmin\tmax\n' > "${aggregate_tmp}"
    for source_pdb in "${pdb_files[@]}"; do
        pdb_filename="$(basename -- "${source_pdb}")"
        target_name="${pdb_filename%.*}"
        target_summary="${RESULTS_DIR}/${target_name}/analysis/summary.tsv"
        [[ -s "${target_summary}" ]] || continue
        awk -v target="${target_name}" 'NR>1 { print target "\t" $0 }' \
            "${target_summary}" >> "${aggregate_tmp}"
    done
    mv -- "${aggregate_tmp}" "${aggregate}"
    log "Combined summary: ${aggregate}"
fi

log 'All requested PDB workflows completed.'
